---
- set_fact: branch="master"

- name: Checkout redhat quickstarts
  git:
    repo: "https://github.com/Estafet-LTD/containers-quickstarts.git"
    dest: "{{ workdir }}/containers-quickstarts"
    version: "{{ branch }}"
    update: yes
  tags:
    - git  

- set_fact: quickstarts="{{ workdir }}/containers-quickstarts"
