---
- name: Install the Jenkins master server
  shell: "oc new-app jenkins-persistent -p VOLUME_CAPACITY={{ volume_capacity }} -p MEMORY_LIMIT={{ memory_limit }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins   

- name: Wait for the jenkins master server to become available
  shell: "oc rollout status dc/jenkins"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins  
