---
# app cleanup    
- name: Remove all aspects of the application so that we can rebuild from scratch
  shell: "oc delete all -l app={{ microservice.name }} -n {{ project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  