---
- name: Load the variables from {{ secret_yml }}
  include_vars:
    file: "{{ secret_yml }}"

- name: Initialise secret variables
  set_fact: 
    secretStr: ""

- name: format the secrets variables
  set_fact: 
    secretStr: "{{ secretStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ secrets }}"

- name: Create the {{ microservice.name }} secrets
  shell: 'oc create secret generic {{ microservice.name }} {{ secretStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift