---
- name: Load the variables from {{ config_yml }}
  include_vars:
    file: "{{ config_yml }}"

- name: Initialise config map variables
  set_fact: 
    mapStr: ""

- name: format the configmap variables
  set_fact: 
    mapStr: "{{ mapStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ config_map }}"

- name: Create the {{ microservice.name }} configmap
  shell: 'oc create configmap {{ microservice.name }} {{ mapStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
