---
# create config maps    
- name: Check that the {{ stage }}-config.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/{{ stage }}-config.yml"
  register: stat_result
  
- name: initialise the config
  set_fact:
    config: ""

- name: define the {{ stage }}-config.yml file
  set_fact:
    config: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/{{ stage }}-config.yml"
  when: stat_result.stat.exists

- name: define the default config file
  set_fact:
    config: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/default-config.yml"
  when: config == ""

- name: Load the variables from {{ config }}
  include_vars:
    file: "{{ config }}"

- name: Initialise config map variables
  set_fact: 
    mapStr: ""

- name: format the configmap variables
  set_fact: 
    mapStr: "{{ mapStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ config_map }}"

- name: Create the {{ microservice.name }} configmap
  shell: 'oc create configmap {{ microservice.name }} {{ mapStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
