---
# setup   
- name: load the settings from {{ setup_yml }}
  include_vars:
    file: "{{ setup_yml }}"
  when: setup_yml != ""

- name: invoke dynamic role
  include_role: 
    name: "{{ item.name }}"
  vars:
    params: "{{ item }}"
  with_items: "{{ setup | default([]) }}"
  when: not image_deployed