---
- name: Install jmespath
  shell: "pip install jmespath"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - jmespath 
