---
- include_role: 
    name: boostcd._namespace_setup
  vars:
    project: "{{ boost_project }}"
    project_description: "Boost Test"

- include_role: 
    name: boostcd.amq_setup
  vars:
    project: "{{ boost_project }}"
    params: "{{ amq_params }}"

- include_role: 
    name: boostcd.jaeger_setup
  vars:
    project: "{{ boost_project }}"

- include_role: 
    name: boostcd.postgresql_setup
  vars:
    project: "{{ boost_project }}"

- include_role: 
    name: boostcd.pgadmin_setup
  vars:
    project: "{{ boost_project }}"

- include_role: 
    name: boostcd._add_boost_jenkins_role
  vars:
    project: "{{ boost_project }}"
    role: edit    