---

- debug:
    var: params
    verbosity: 0

- name: Create the {{ microservice.name }} database on PostgreSQL Pod
  shell: 'oc exec {{db_pod}} -- /bin/sh -i -c "createdb {{ project }}-{{ microservice.name }}"'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - postgresql

- name: Copy ddl to PostgreSQL Pod
  shell: 'oc rsync --no-perms=true --include="*.ddl" --exclude="*" {{ workdir }}/{{ microservice.repo }}/ddl/ {{pod}}:/tmp'
  register: command_result
  when: params.reset_db 
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - postgresql

- name: Execute Drop ddl on PostgreSQL Pod
  shell: 'oc exec {{db_pod}} -- /bin/sh -i -c "psql -d {{ project }}-{{ microservice.name }} -U postgres -f /tmp/drop-{{ microservice.name }}-db.ddl"'
  register: command_result
  when: params.reset_db
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - postgresql
    
- name: Drop liquibase on PostgreSQL Pod
  shell: 'oc exec {{db_pod}} -- /bin/sh -i -c "psql -d {{ project }}-{{ microservice.name }} -U postgres -f /tmp/drop-liquibase-db.ddl"'
  register: command_result
  when: params.reset_db
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - postgresql    