---
- debug:
    var: params
    verbosity: 0

- name: Restart {{ params.app }}
  shell : "oc rollout latest dc/{{ params.app }} -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Wait for the {{ params.app }} to become available again
  shell: "oc rollout status dc/{{ params.app }} -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift