---
- debug:
    var: params
    verbosity: 0

- name: Delete "{{ params.bucket }}" bucket on Couchbase Pod
  uri:
    url: http://couchbase.{{ project }}.svc:8091/pools/default/buckets/{{ project }}-{{ params.bucket }}
    method: DELETE
    user: "{{ couchbase.user }}"
    password: "{{ couchbase.password }}"
    status_code: 200, 202, 404
  when: reset is defined and reset

- name: Create the "{{ params.bucket }}" bucket on Couchbase Pod
  uri:
    url: http://couchbase.{{ project }}.svc:8091/pools/default/buckets
    method: POST
    user: "{{ couchbase.user }}"
    password: "{{ couchbase.password }}"  
    body_format: form-urlencoded
    body:
      name: "{{ project }}-{{ params.bucket }}"
      flushEnabled: '1'
      ramQuotaMB: '100'
      bucketType: 'couchbase'
      authType: 'sasl'
      saslPassword: "{{ params.bucket_password }}"
    force_basic_auth: yes
    status_code: 200, 202, 400 