---
- debug:
    var: params
    verbosity: 0

- name: Delete "{{ params.bucket }}" bucket on Couchbase Pod
  uri:
    url: http://couchbase-{{ project }}.{{ openshift_host }}/pools/default/buckets/{{ params.bucket }}
    method: DELETE
    user: "{{ couchbase_user }}"
    password: "{{ couchbase_password }}"
    status_code: 200, 404

- name: Create the "{{ params.bucket }}" bucket on Couchbase Pod
  uri:
    url: http://couchbase-{{ project }}.{{ openshift_host }}/pools/default/buckets
    method: POST
    user: "{{ couchbase_user }}"
    password: "{{ couchbase_password }}"  
    body_format: form-urlencoded
    body:
      name: "{{ project }}-{{ params.bucket }}"
      ramQuotaMB: '100'
      bucketType: 'couchbase'
      authType: 'sasl'
      saslPassword: "{{ params.bucket_password }}"
    force_basic_auth: yes
    status_code: 202