---
- include_role: 
    name : init

- set_fact: prod_project="{{ product }}-prod"

- name: Switch to Namespace {{ prod_project }}
  shell: "oc project {{ prod_project }}"
  tags:
    - openshift  

- name: Create a routes to expose the application
  shell: "oc process -f {{ templates }}/prod-route.yml -p MICROSERVICE_NAME={{ item.name }} -p PRODUCT={{ product}} | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: "{{ item.expose }}"
  with_items: "{{ microservices }}"
  tags:
    - openshift  
