---
- name: Loading all json stubs from {{ params.json_dir }}
  include_role: 
    name: boostcd._wiremock_json
  vars:
    json: "{{ item }}"      
  with_fileglob:
    - "{{ workdir }}/{{ params.repo }}/{{ params.json_dir }}/*.json"