---
- name: Create the jenkins image management slave
  shell: "oc process -f {{ quickstarts }}/.openshift/templates/jenkins-slave-generic-template.yml -p NAME=jenkins-slave-image-mgmt -p SOURCE_CONTEXT_DIR=jenkins-slaves/jenkins-slave-image-mgmt | oc create -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - openshift       
