--- 

- debug:
    var: params
    verbosity: 0

- set_fact: mq_project="{{ product.name }}-mq-{{ params.colour }}"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ mq_project }}"
    project_description: "MQ {{ params.colour }}: {{ product.description }}"

- include_role: 
    name: amq-setup
  vars:
    project: "{{ mq_project }}"

