---
- name: Retrieve the kube from the downloaded credentials
  xml:
    path: "{{ roles }}/_jenkins_credentials_xml/downloads/credentials.xml"
    xpath: /com.cloudbees.plugins.credentials.SystemCredentialsProvider/domainCredentialsMap/entry/java.util.concurrent.CopyOnWriteArrayList/org.jenkinsci.plugins.kubernetes.credentials.FileSystemServiceAccountCredential/id
    content: text
  register: kube_id

- debug:
    var: kube_id
    verbosity: 0

- name: Set the kube to the credentials template
  xml:
    path: "{{ roles }}/_jenkins_credentials_xml/files/credentials.xml"
    xpath: /com.cloudbees.plugins.credentials.SystemCredentialsProvider/domainCredentialsMap/entry/java.util.concurrent.CopyOnWriteArrayList/org.jenkinsci.plugins.kubernetes.credentials.FileSystemServiceAccountCredential/id
    value: "{{ kube_id.matches[0].id }}"