---
- debug:
    var: params
    verbosity: 0

- name: Verify that the database host has been defined
  fail:
    msg: "[Database host] is not set. Please set params external_postgres_database"
  when: params.external_postgres_database is undefined

- name: Create the service for external database 
  shell: "oc process -f {{ templates }}/database-service.yml -p DB_HOST={{ params.external_postgres_database }} | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - db
    - postgresql

    