---
- set_fact: console_project="{{ product.name }}-console"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ console_project }}"
    project_description: "Console: {{ product.description }}"

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ console_project }}"
    role: view

- include_role: 
    name: amq-setup
  vars:
    project: "{{ console_project }}"
    params: "{{ amq_params }}"

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ console_project }}"   

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ console_project }}"

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    microservice: "{{ item }}" 
    docker_registry: "{{ microservices_boost_projects.docker_registry }}"
    maven_mirror_url: "{{ microservices_boost_projects.maven_mirror_url }}"     
    project: "{{ console_project }}"
  with_items: "{{ microservices_boost_projects.apps }}"
  tags:
    - openshift
