---
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ console_project }}"
    project_description: "Console: {{ product.description }}"

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ console_project }}"
    role: view

- include_role: 
    name: amq-setup
  vars:
    project: "{{ console_project }}"
    params: "{{ amq_params }}"

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ console_project }}"

- name: Deploy the microservices
  include_role:
    name: deploy-app
  vars:
    microservice: "{{ item }}" 
    docker_registry: "{{ console_environment.docker_registry }}"
    maven_mirror_url: "{{ console_environment.maven_mirror_url }}"     
    project: "{{ console_project }}"
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift
