---
- include_role: 
    name : init

- set_fact: console_project="{{ product }}-console"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ console_project }}"
    project_description: "Console: {{ product_description }}"
    cloud_environment: true

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ console_project }}"
    role: view

- include_role: 
    name: amq-setup
  vars:
    project: "{{ console_project }}"
    templates_project: openshift

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ console_project }}"   

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ console_project }}"

- include_role: 
    name: db-pod
  vars:
    project: "{{ console_project }}"

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    microservice: "{{ item }}" 
    db_type: local
    db_pod: "{{ local_db_pod }}"
    reset_db: true
    imagestream_namespace: openshift
    docker_registry: docker-registry.default.svc:5000
    maven_mirror_url: http://nexus.nexus.svc:8081/nexus/content/groups/public 
    test: false    
    project: "{{ console_project }}"
  with_items: "{{ microservices_boost_projects }}"
  tags:
    - openshift
