---
# Project definition - add new microservices here
microservices_boost_projects:
  - name: console-trello-api
    repo: estafet-openshift-boost-console-api-trello
    db: false
    expose: false       
    environment_variables:        
      - name: TRELLO_ACCESS_TOKEN
        value: "{{ trello_access_token }}"
      - name: TRELLO_API_KEY
        value: "{{ trello_api_key }}"
        
    