---
# Define the name and description of the OpenShift project
- set_fact: nexus_project="nexus"

- include_role: 
    name: _namespace_setup
  vars:
    project: "{{ nexus_project }}"
    project_description: "Nexus"

- include_role: 
    name: _namespace_role_setup
  vars:
    project: "{{ nexus_project }}"
    role: view

- name: Install the Nexus repository server
  shell: "oc new-app sonatype/nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  
    
- name: Wait for the nexus server to become available
  shell : "oc rollout status deployment nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  
    - nexus

- name: Expose the nexus service
  shell: "oc expose svc/nexus --path='/nexus'"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Configure the liveness probe
  shell: "oc set probe deployment/nexus --liveness --failure-threshold 3 --initial-delay-seconds 30 -- echo ok"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Configure the readiness probe
  shell: "oc set probe deployment/nexus --readiness --failure-threshold 3 --initial-delay-seconds 30 --get-url=http://:8081/nexus/content/groups/public"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Wait for the nexus server to become available
  shell : "oc rollout status deployment nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  
    - nexus

- name: Configure the persistent storage for nexus
  shell: "oc set volume deployment/nexus --add --name 'nexus-volume-1' --type 'pvc' --mount-path '/sonatype-work/' --claim-name 'nexus-pv' --claim-size '20G' --overwrite"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Wait for the nexus server to become available
  shell : "oc rollout status deployment nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  
    - nexus
    