---
- name: Create the couchbase cluster
  shell: "oc process -f {{ actions }}/boostcd.couchbase_setup/files/couchbase.yml -p COUCHBASE_USERNAME={{ couchbase.user | b64encode }} -p COUCHBASE_PASSWORD={{ couchbase.password | b64encode }} -p PRODUCT={{ product.name }} | oc create -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift   