---
- name: Create the couchbase cluster
  shell: "oc process -f {{ actions }}/boostcd.couchbase_setup/files/couchbase.yml -p COUCHBASE_USERNAME={{ couchbase.user | b64encode }} -p COUCHBASE_PASSWORD={{ couchbase.password | b64encode }} -p PRODUCT={{ product.name }} | oc create -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift   

- set_fact: 
    match_pod: "cb-{{ product.name }}"

- name: Wait for pods to start
  shell: "oc get pods -n {{ project }} -o json"
  register: list_of_pods
  until: "{{ list_of_pods.stdout | match_count(match_pod) }} == 3"
  retries: 30
  delay: 5

- name: Expose Service cb-{{ product.name }}
  shell: "oc expose service cb-{{ product.name }}-ui"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift


