---
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ boost_project }}"
    project_description: "Boost Development"

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ boost_project }}"

- include_role: 
    name: jenkins-setup
  vars:
    project: "{{ boost_project }}"
    volume_capacity: 10Gi
    memory_limit: 2Gi

- name: Delete the all pipelines
  shell: "oc delete bc --all -n {{ boost_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - openshift 

- include_role: 
    name: boost-libraries-setup
  vars:
    project: "{{ boost_project }}"
    
- name: Create build and release pipelines for each of the microservices
  shell: "oc process -f {{ templates }}/console-microservice-pipelines.yml -p GITHUB={{ github.org }} -p MICROSERVICE_NAME={{ item.name }} -p MICROSERVICE_REPO_URI={{ item.repo }} -p PRODUCT={{ product.name }} -p MICROSERVICE_REPO_URI={{ item.repo }} -p BUILD_PIPELINE={{ item.build }} -p RELEASE_PIPELINE={{ item.release }} | oc create -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ microservices }}"
  tags:
    - openshift      