apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: release-boost-framework
parameters:  
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "release-boost-framework"
      type: release
    name: "release-boost-framework"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/boostcd/boostcd"
    strategy:
      jenkinsPipelineStrategy:                         
        jenkinsfilePath: src/boost/openshift/pipelines/release-boost-framework.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0    