apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: boost-library-pipelines
parameters:
- description: Defines name of the library
  name: LIBRARY_NAME
  required: true    
- description: Defines the git repository uri within which the library resides
  name: LIBRARY_REPO_URI
  required: true      
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true   
- description: Defines the build library
  name: BUILD_LIBRARY
  required: true  
- description: Defines the release library
  name: RELEASE_LIBRARY
  required: true  
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "build-${LIBRARY_NAME}"
      type: build-library
      product: ${PRODUCT}
    name: "build-${LIBRARY_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/boostcd/boostcd"
    strategy:
      jenkinsPipelineStrategy:
        env:                 
          - name: REPO
            value: ${LIBRARY_REPO_URI}            
        jenkinsfilePath: src/boost/openshift/pipelines/${BUILD_LIBRARY}
      type: JenkinsPipeline
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "release-${LIBRARY_NAME}"
      type: release-library
      product: ${PRODUCT}
    name: "release-${LIBRARY_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/boostcd/boostcd"
    strategy:
      jenkinsPipelineStrategy:
        env:          
          - name: REPO
            value: ${LIBRARY_REPO_URI}                       
        jenkinsfilePath: src/boost/openshift/pipelines/${RELEASE_LIBRARY}
      type: JenkinsPipeline
  status:
    lastVersion: 0