apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: console-microservice-pipelines
parameters:
- description: Defines the location of the estafet dockerhub
  name: DOCKERHUB
  required: true  
- description: Defines name of the microservice
  name: MICROSERVICE_NAME
  required: true
- description: Defines the git repository uri within which the microservice resides
  name: MICROSERVICE_REPO_URI
  required: true    
- description: Defines build pipeline
  name: BUILD_PIPELINE
  required: true   
- description: Defines release pipeline
  name: RELEASE_PIPELINE
  required: true     
- description: Defines host and port of the openshift cluster
  name: OPENSHIFT_HOST_PORT
  required: true  
- description: Defines boost url
  name: BOOST_URL
  required: true    
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "build-boost-${MICROSERVICE_NAME}"
      type: build
    name: "build-boost-${MICROSERVICE_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${BOOST_URL}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: MICROSERVICE
            value: ${MICROSERVICE_NAME}                                 
        jenkinsfilePath: src/boost/openshift/pipelines/${BUILD_PIPELINE}
      type: JenkinsPipeline
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "release-boost-${MICROSERVICE_NAME}"
      type: release
    name: "release-boost-${MICROSERVICE_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${BOOST_URL}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: DOCKERHUB
            value: ${DOCKERHUB}
          - name: REPO
            value: ${MICROSERVICE_REPO_URI}
          - name: MICROSERVICE
            value: ${MICROSERVICE_NAME}      
          - name: OPENSHIFT_HOST_PORT
            value: ${OPENSHIFT_HOST_PORT}                                       
        jenkinsfilePath: src/boost/openshift/pipelines/${RELEASE_PIPELINE}
      type: JenkinsPipeline
  status:
    lastVersion: 0    