apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: promote-all-to-prod
parameters: 
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true
- description: Defines boost version
  name: VERSION
  required: true      
- description: Defines the environment that this pipeline is related to
  name: ENV
  required: true      
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: promote-all-to-prod
      product: ${PRODUCT}
    name: promote-all-to-prod
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/Estafet-LTD/estafet-openshift-boost"
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PRODUCT
            value: ${PRODUCT}        
          - name: PROJECT
            value: "${PRODUCT}-${ENV}"  
        jenkinsfilePath: setup-environments/pipelines/promote-all-to-prod.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0