apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: promote-all
parameters: 
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true
- description: Defines boost url
  name: BOOST_URL
  required: true      
- description: Defines boost version
  name: VERSION
  required: true        
- description: Defines the environment that this pipeline is related to
  name: ENV
  required: true      
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "promote-all-${ENV}"
      product: ${PRODUCT}
    name: "promote-all-${ENV}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${BOOST_URL}
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PRODUCT
            value: ${PRODUCT}        
          - name: PROJECT
            value: "${PRODUCT}-${ENV}"  
        jenkinsfilePath: src/boost/openshift/pipelines/promote-all.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0    