apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: promote-pipelines
parameters:
- description: Defines name of the microservice
  name: MICROSERVICE_NAME
  required: true
- description: Defines the git repository uri within which the microservice resides
  name: MICROSERVICE_REPO_URI
  required: true    
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true   
- description: Defines boost url
  name: BOOST_URL
  required: true       
- description: Defines boost version
  name: VERSION
  required: true      
- description: Defines the environment that this pipeline is related to
  name: ENV
  required: true    
- description: Defines the project that this pipeline is related to
  name: PROJECT
  required: true
- description: Defines the main repository that contains the infrastructor definition
  name: ENVIRONMENTS_REPO_URI
  required: true       
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "promote-${ENV}-${MICROSERVICE_NAME}"
      type: promote
      product: ${PRODUCT}
    name: "promote-${ENV}-${MICROSERVICE_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${BOOST_URL}
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:   
          - name: PRODUCT
            value: ${PRODUCT}       
          - name: PRODUCT_REPO
            value: ${ENVIRONMENTS_REPO_URI}                    
          - name: REPO
            value: ${MICROSERVICE_REPO_URI}
          - name: MICROSERVICE
            value: ${MICROSERVICE_NAME}
          - name: PROJECT
            value: ${PROJECT}
        jenkinsfilePath: "src/boost/openshift/pipelines/promote.jenkinsFile"
      type: JenkinsPipeline
  status:
    lastVersion: 0
