apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: test-pipelines
parameters:
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true
- description: Defines the environment that this pipeline is related to
  name: ENV
  required: true      
- description: Defines repo that contains the test for the specified environment
  name: REPO_URI
  required: true
- description: Defines product repo that contains the test for the specified environment
  name: PRODUCT_REPO_URI
  required: true
- description: Defines repo that contains the test for the specified environment
  name: SMOTE_TEST_REPO_URI
  required: true
- description: Defines boost url
  name: BOOST_URL
  required: true    
- description: Defines boost version
  name: VERSION
  required: true     
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: qa-${ENV}
      product: ${PRODUCT}
    name: qa-${ENV}
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${BOOST_URL}
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:          
          - name: PRODUCT
            value: ${PRODUCT}     
          - name: PRODUCT_REPO
            value: ${PRODUCT_REPO_URI}            
          - name: REPO
            value: ${REPO_URI}
          - name: ENV
            value: ${ENV}          
          - name: PROJECT
            value: some_project                                                
        jenkinsfilePath: src/boost/openshift/pipelines/testWrapper.jenkinsFile
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic    
  status:
    lastVersion: 0    
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: qa-${ENV}-impl
      product: ${PRODUCT}
    name: qa-${ENV}-impl
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${REPO_URI}
    strategy:
      jenkinsPipelineStrategy:
        env:           
          - name: PRODUCT
            value: ${PRODUCT}     
          - name: REPO
            value: ${REPO_URI}
          - name: PROJECT
            value: some_project                                                
        jenkinsfilePath: src/boost/openshift/pipelines/test.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0      
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: qa-${ENV}-smoke-test
    name: qa-${ENV}-smoke-test
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${SMOTE_TEST_REPO_URI}
    strategy:
      jenkinsPipelineStrategy:
        env:          
          - name: PRODUCT
            value: ${PRODUCT}     
          - name: REPO
            value: ${REPO_URI}
          - name: ENV
            value: ${ENV}          
          - name: PROJECT
            value: some_project   
        jenkinsfilePath: src/boost/openshift/pipelines/test.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0                     