---
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ boost_project }}"
    project_description: "Boost CI/CD"

- name: Delete the all build pipelines
  shell: "oc delete bc build-boost-{{ item.name }} -n {{ boost_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift 

- name: Delete the all release pipelines
  shell: "oc delete bc release-boost-{{ item.name }} -n {{ boost_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift 

- name: Delete the publish image pipeline
  shell: "oc delete bc publish-image -n {{ boost_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - openshift 
