---
- include_role: 
    name : init

- set_fact: monitoring_project="{{ product }}-monitoring"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ monitoring_project }}"
    project_description: "Monitoring: {{ product_description }}"
    cloud_environment: true

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ monitoring_project }}"
    role: view

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ monitoring_project }}"   

- include_role: 
    name: pgadmin-setup
  vars:
    project: "{{ monitoring_project }}"   

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ monitoring_project }}"

- include_role: 
    name: db-pod
  vars:
    project: "{{ monitoring_project }}"

- debug:
  var: microservices_boost_projects

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}" 
    expose: "{{ item.expose }}"    
    db: "{{ item.db }}"
    env_vars: "{{ item.environment_variables }}"
    imagestream_namespace: openshift
    docker_registry: docker-registry.default.svc:5000
    maven_mirror_url: http://nexus.nexus.svc:8081/nexus/content/groups/public 
    test: false    
    project: "{{ monitoring_project }}"
  with_items: "{{ microservices_boost_projects }}"
  tags:
    - openshift
