---
- include_role: 
    name : init

- set_fact: project=microservices-scrum
    
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ project }}"
    project_description: "{{ product_description }}"
    cloud_environment: false

- include_role: 
    name: imagestream-setup
  vars:
    project: "{{ project }}"

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ project }}"   

- include_role: 
    name: wiremock-setup
  when: "not {{ test_environment }}"
  vars:
    project: "{{ project }}"
    tag: 2.25.1

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ project }}"

- include_role: 
    name: amq-setup
  vars:
    project: "{{ project }}"
    templates_project: "{{ project }}"

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}" 
    expose: "{{ item.expose }}"    
  with_items: "{{ microservices }}"
  tags:
    - openshift
