---
- include_role: 
    name : init

- name: Verify that the maven mirror url has been defined
  fail:
    msg: "[Maven Mirror Url] is not set. Please edit inventory"
  when: maven_mirror_url is undefined

- name: Verify that the docker registry host and port has been defined
  fail:
    msg: "[Docker Registry Host and Port] is not set. Please edit inventory"
  when: docker_registry is undefined

- set_fact: local_project=microservices-scrum
    
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ local_project }}"
    project_description: "{{ product_description }}"
    cloud_environment: false

- include_role: 
    name: imagestream-setup
  vars:
    project: "{{ local_project }}"

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ local_project }}"   

- include_role: 
    name: wiremock-setup
  when: not test
  vars:
    project: "{{ local_project }}"
    tag: 2.25.1

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ local_project }}"

- include_role: 
    name: db-pod
  vars:
    project: "{{ local_project }}"

- include_role: 
    name: amq-setup
  vars:
    project: "{{ local_project }}"
    templates_project: "{{ local_project }}"

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}" 
    expose: true    
    db: "{{ item.db }}"
    db_pod: "{{ local_db_pod }}"
    project: "{{ local_project }}"
  with_items: "{{ microservices }}"
  tags:
    - openshift
