---
- include_role: 
    name : init

- name: Verify that the maven mirror url has been defined
  fail:
    msg: "[Maven Mirror Url] is not set. Please edit inventory"
  when: maven_mirror_url is undefined

- name: Verify that the docker registry host and port has been defined
  fail:
    msg: "[Docker Registry Host and Port] is not set. Please edit inventory"
  when: docker_registry is undefined

- set_fact: project=microservices-scrum
    
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ project }}"
    project_description: "{{ product_description }}"
    cloud_environment: false

- include_role: 
    name: imagestream-setup
  vars:
    project: "{{ project }}"

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ project }}"   

- include_role: 
    name: wiremock-setup
  when: not test
  vars:
    project: "{{ project }}"
    tag: 2.25.1

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ project }}"

- include_role: 
    name: amq-setup
  vars:
    project: "{{ project }}"
    templates_project: "{{ project }}"

- name: Read the database pod list
  shell: "oc get pods --selector app=postgresql -o json"
  register: list_of_db_pods
    
- name: Get the name of the PostgreSQL Pod
  set_fact: db_pod="{{list_of_db_pods.stdout|from_json|json_query('items[0].metadata.name')}}"

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}" 
    expose: "{{ item.expose }}"    
    db: "{{ item.db }}"
    db_pod: "{{ db_pod }}"
  with_items: "{{ microservices }}"
  tags:
    - openshift
