---
- name: Check that the {{ plug_in }}.tgz exists
  stat:
    path: "{{ path }}/{{ plug_in }}.tar.gz"
  register: stat_result

- name: "Extract {{ plug_in }}.tgz into {{ plugins_path }}/files"
  unarchive:
    src: "{{ plugins_path }}/{{ plug_in }}.tar.gz"
    dest: "{{ plugins_path }}"
  when: stat_result.stat.exists

- name: remove the plugin archive
  shell: "rm {{ plugins_path }}/{{ plug_in }}.tar.gz | true"

