---
- name: Install Estafet Openshift Boost Console
  hosts: local
  vars:
    workdir: "{{ ansible_env.HOME }}/.estafet"
    project: boost-console
    project_description: "Openshift Boost Console" 
  vars_files:
    - variables/create-local-boost-console-vars.yml
    - variables/boost-console-microservices-vars.yml
  tasks:  
    - include: roles/init.yml
    - include: roles/namespace-setup.yml
    - include: roles/jaeger-setup.yml
    - include: roles/imagestream-setup.yml  
    - include: roles/create-boost-console-app.yml
