---
- name: Install Local Test Environment
  hosts: local 
  tasks:          
    - include_role:
        name: local-environment-setup    
      vars:
        test: true
        local_project: "microservices-scrum"

