---
- name: Preparing the ansible roles for openshift boost 
  hosts: local   
  vars:
    workdir: "~/.estafet"  
  tasks:
   
    - name: Create Workdir
      file:
        path: "{{ workdir }}"
        state: directory
        
    - name: Checkout the boost console dependencies from github
      git:
        repo: "https://github.com/{{ github }}/estafet-openshift-boost.git"
        dest: "{{ workdir }}/estafet-openshift-boost"
        update: yes
      tags:
        - git  

         
  
