---
- name: Preparing the ansible roles for openshift boost 
  hosts: local   
  vars:
    workdir: "~/.estafet"  
  tasks:
   
    - name: Create Workdir
      file:
        path: "{{ workdir }}"
        state: directory
        
    - name: Checkout the boost console dependencies from github
      git:
        repo: "https://github.com/{{ github }}/estafet-openshift-boost.git"
        dest: "{{ workdir }}/estafet-openshift-boost"
        update: yes
      tags:
        - git  

    - name: Updating playbooks
      copy:
        src: "{{ item }}"
        dest: . 
        force: yes       
      with_fileglob:
      - "{{ workdir }}/estafet-openshift-boost/setup-environments/*.yml"

    - name: Updating roles
      copy:
        src: "{{ workdir }}/estafet-openshift-boost/setup-environments/roles"
        dest: "~/.ansible"
        force: yes