---
- name: Run the Release Pipelines for Libraries
  hosts: local      
  tasks:          
    - include_role:
        name: run-library-pipelines    
      vars:
        type: release
         
  
