---
- include_role: 
    name : init
  when: openshift_connected is undefined or not openshift_connected

- debug:
    var: env
    verbosity: 0

- set_fact: stage_project="{{ product }}-{{ env.name }}"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ stage_project }}"
    project_description: "{{ env.display }}: {{ product_description }}"
    cloud_environment: true
    next: "{{ product }}-{{ env.next }}"
    display: "{{ env.display }}"

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ stage_project }}"
    role: env.role
  when: env.role is defined

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ stage_project }}"
    params: "{{ item }}"
  with_items: "{{ env.roles | default([]) }}"

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ stage_project }}"
    params: "{{ item }}"
  with_items: "{{ env.ext_roles | default([]) }}"
  
- include_role: 
    name: add-jenkins-role
  vars:
    project: "{{ stage_project }}"
    role: edit
