---

- name:  create a new webhook for the microservices
  github_webhook:
    repository: "{{ item.repo | github_repo }}"
    url: "http://console-gateway-api-{{ product.name }}-console.{{ openshift.subdomain }}/github/hooks/"
    content_type: json
    events:
      - push
    user: "{{ github.user }}"
    password: "{{ github.password }}"
    state: present
  with_items: "{{ microservices }}"

- name:  create a new webhook for the tests
  github_webhook:
    repository: "{{ item.test_repo | github_repo }}"
    url: "http://console-gateway-api-{{ product.name }}-console.{{ openshift.subdomain }}/github/hooks/"
    content_type: json
    events:
      - push
    user: "{{ github.user }}"
    password: "{{ github.password }}"
    state: present
  when: item.test_repo is defined
  with_items: "{{ environments.stages }}"        
