---
- include_role: 
    name : init
  when: openshift_connected is undefined or not openshift_connected

- name: Verify that the cloud project has been defined
  fail:
    msg: "[Cloud Project] is not set. Please edit inventory"
  when: cloud_project is undefined

- name: Switch to Namespace {{ cloud_project }}
  shell: "oc project {{ cloud_project }}"
  tags:
    - openshift  

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ cloud_project }}"   

- include_role: 
    name: amq-setup
  vars:
    project: "{{ cloud_project }}"
    templates_project: openshift  
  when: username == "admin"    

- include_role: 
    name: wiremock-setup
  when: not test
  vars:
    project: "{{ cloud_project }}"
    tag: 2.25.1
    expose: true
  when: username == "admin"

- name: Create the microservices
  include_role:
    name: create-app
  vars:
    microservice: "{{ item }}" 
    db_type: cloud
    imagestream_namespace: openshift
    docker_registry: docker-registry.default.svc:5000
    maven_mirror_url: http://nexus.nexus.svc:8081/nexus/content/groups/public  
    project: "{{ cloud_project }}"
  when: not item.ignore    
  with_items: "{{ microservices }}"
  tags:
    - openshift
