---
- include_vars:
    dir: vars
    extensions: [yml]
    
- set_fact: openshift_host_port="{{ openshift.host }}:{{ openshift.port }}"
  when: openshift.port is defined

- set_fact: openshift_host_port="{{ openshift.host }}"
  when: openshift.port is not defined
    
- name: Verify if openshift is set
  fail:
    msg: "[OpenShift host] is not defined. Please edit project-vars.yml"
  when: openshift is undefined

- name: Verify if product variable is set
  fail:
    msg: "[Product] is not defined. Please edit project-vars.yml"
  when: product is undefined

- name: Verify if the microservices have been defined
  fail:
    msg: "[Microservices Definitions] are not set. Please edit microservices-vars.yml"
  when: microservices is undefined

- name: Verify if the environments have been defined
  fail:
    msg: "[Environments Definitions] are not set. Please edit environments-vars.yml"
  when: environments is undefined

- name: Verify if the libraries have been defined
  fail:
    msg: "[Library Definitions] are not set. Please edit libraries-vars.yml"
  when: libraries is undefined

- name: Verify if the users have been defined
  fail:
    msg: "[Users] are not set. Please edit users-vars.yml"
  when: users is undefined

- name: Verify if the tasks manager has been defined
  fail:
    msg: "[Task Manager] are not set. Please edit project-vars.yml"
  when: task_manager is undefined

- name: Verify if the tasks manager has been defined
  fail:
    msg: "[Task Manager Title] are not set. Please edit project-vars.yml"
  when: task_manager is undefined

- name: Login in OpenShift as {{ openshift.username }}
  shell: "oc login --insecure-skip-tls-verify=true -u {{ openshift.username }} -p {{ openshift.password }} {{ openshift_host_port }}"
  tags:
    - openshift

- set_fact: boost_ddl={{ workdir }}/estafet-openshift-boost/setup-environments/ddl
- set_fact: templates={{ workdir }}/estafet-openshift-boost/setup-environments/templates
- set_fact: objects={{ workdir }}/estafet-openshift-boost/setup-environments/objects
