---
- name: Allows staging to access the production environment
  shell: "oc policy add-role-to-user system:image-puller system:serviceaccount:{{ project }}:default -n staging"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins   


    