---
- name: Allows jenkins to access the {{ project }} namespace
  shell: "oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins   


    