---
- name: Create the service for external database 
  shell: "oc process -n {{ project }} -f {{ inventory_dir }}/templates/database-service.yml -p DB_HOST={{ database }} | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - db
    - postgresql

    