---
- name: Create the pgadmin4
  shell: "oc process -n {{ project }} -f {{ inventory_dir }}/templates/pgadmin4.yml | oc create -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - openshift
    - pgadmin
  
- name: Wait for the pgadmin  server to become available
  shell : "oc rollout status dc/pgadmin -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - wiremock    

    