---
# Define the name and description of the OpenShift project
- set_fact: project="prod"
- set_fact: project_description="Production - Microservices Scrum"

- include: namespace-setup.yml
- include: add-namespace-view-role.yml
- include: jaeger-setup.yml
- include: external-db.yml
- include: add-jenkins-role.yml

- name: Create a route to expose the application
  shell: "oc process -n {{ project }} -f {{ inventory_dir }}/templates/prod-route.yml -p MICROSERVICE_NAME={{ item.name }} | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift  
