---
- include_role: 
    name : init

- name: Verify if the internal openshift host is set
  fail:
    msg: "[Internal OpenShift host] is not defined. Please edit inventory"
  when: openshift_internal is undefined

- name: Create the boost console applications
  include_role: 
    name: create-boost-console-app
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}"
    cpu_min: "{{ item.cpu_min }}"
    cpu_max: "{{ item.cpu_max }}"
    memory_min: "{{ item.memory_min }}"
    memory_max: "{{ item.memory_max }}"   
    expose: "{{ item.expose }}" 
  with_items: "{{ microservices_boost_projects }}"
  tags:
    - openshift
    