---
- include_role: 
    name : init
  when: openshift_connected is undefined or not openshift_connected

- include_role: 
    name : nexus-setup

- include_role: 
    name: update-environments

- include_role: 
    name: prod-route-setup
 
- include_role: 
    name: console-environment-setup
    
- include_role: 
    name: monitoring-environment-setup  