---
- include_role: 
    name : init

- include_role: 
    name : nexus-setup

- include_role: 
    name: update-environments

- include_role: 
    name: prod-route-setup

- include_role: 
    name: mq-namespace-setup
  vars:
    colour: green

- include_role: 
    name: mq-namespace-setup
  vars:
    colour: blue
 
- include_role: 
    name: monitoring-environment-setup
    
  