---
- include_role: 
    name : init

- include_role: 
    name : nexus-setup

- include_role: 
    name : cicd-environment-setup
        
- include_role: 
    name: build-environment-setup

- include_role: 
    name: test-environment-setup
    
- include_role: 
    name: monitoring-environment-setup
    
- include_role: 
    name: prod-environment-setup

  