---
- include_role: 
    name : init
  when: openshift_connected is undefined or not openshift_connected

- set_fact: build_project="{{ product }}-build"    
- name: "Updating users for {{ build_project }}"
  include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ build_project }}"
    role: edit   
    
- set_fact: test_project="{{ product }}-test"
- name: "Updating users for {{ test_project }}"
  include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ test_project }}"
    role: edit   
     
- set_fact: cicd_project="{{ product }}-cicd"
- name: "Updating users for {{ cicd_project }}"
  include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ cicd_project }}"
    role: edit  
    
- set_fact: monitoring_project="{{ product }}-monitoring"
- name: "Updating users for {{ monitoring_project }}"
  include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ monitoring_project }}"
    role: view  

- set_fact: nexus_project="nexus"
- name: "Updating users for {{ nexus_project }}"
  include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ nexus_project }}"
    role: view  


