---

- debug:
    var: params
    verbosity: 0

- name: Install the JBoss A-MQ Message Broker
  shell: "oc process amq63-basic -n {{ params.templates_project }} -p IMAGE_STREAM_NAMESPACE={{ params.templates_project }} -p MQ_USERNAME={{ params.amq_user }} -p MQ_PASSWORD={{ params.amq_password }} | oc create -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - a-mq        

- name: Remove the readiness probe as some OS implements with ipv4 only stop this from working correctly
  shell: "oc set probe dc/broker-amq --readiness --remove"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - a-mq     

- name: Wait for the a-mq to become available
  shell : "oc rollout status dc/broker-amq"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - a-mq   
