microservice:
  - name: console-ui-react
    repo: estafet-openshift-boost-console-ui-react
    expose: true
    test: false
    environment_variables:
      - name: PRODUCT_DESCRIPTION
        value: "{{ product.description }}"
      - name: OPENSHIFT_HOST
        value: "{{ openshift.host }}"
      - name: TASK_MANAGEMENT_TITLE
        value: "{{ task_manager.title }}"