---
- include_role: 
    name: _namespace_setup
  vars:
    project: boost-services
    project_description: "Boost Services"

- include_role: 
    name: boostcd.amq_setup
  vars:
    project: boost-services
    params: "{{ amq_params }}"

- include_role: 
    name: boostcd.install_postgresql
  vars:
    project: boost-services
    params:
      environment_variables:
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: 500
      template_variables:
        - name: VOLUME_CAPACITY
          value: 3Gi    

- include_role: 
    name: boostcd.jaeger_setup
  vars:
    project: boost-services

- name: Deploy the boost microservices
  include_role:
    name: _deploy_boost_service
  vars:
    microservice: "{{ item }}"     
    docker_registry: "{{ console_environment.docker_registry }}"
    maven_mirror_url: "{{ console_environment.maven_mirror_url }}"     
    project: boost-services
  when: item.name != 'boost-ui' and item.name != 'proxy-api'
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift


