---
- include_role: 
    name: _namespace_setup
  vars:
    project: "{{ boost_project }}"
    project_description: "Boost Test"

- include_role: 
    name: boostcd.amq_setup
  vars:
    project: "{{ boost_project }}"
    params: "{{ amq_params }}"

- include_role: 
    name: boostcd.jaeger_setup
  vars:
    project: "{{ boost_project }}"

- include_role: 
    name: boostcd.install_postgresql
  vars:
    project: "{{ boost_project }}"
    params:
      environment_variables:
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: 200
      template_variables:
        - name: VOLUME_CAPACITY
          value: 2Gi    

- include_role: 
    name: boostcd.pgadmin_setup
  vars:
    project: "{{ boost_project }}"

- include_role: 
    name: _add_boost_jenkins_role
  vars:
    project: "{{ boost_project }}"
    role: edit    