---

- include_role: 
    name: _namespace_setup
  vars:
    project: "{{ observability }}"
    project_description: "Jaeger Operator"

- include_role: 
    name : _install_jaeger_component
  vars:
    project: observability
    component: "crds/jaegertracing.io_jaegers_crd"

- include_role: 
    name : _install_jaeger_component
  vars:
    project: observability
    component: service_account

- include_role: 
    name : _install_jaeger_component
  vars:
    project: observability
    component: cluster_role

- include_role: 
    name : _install_jaeger_component
  vars:
    project: observability
    component: cluster_role_binding

- name: Install Jaeger Operator
  shell: "oc create -n {{ observability }} -f {{ roles }}/_jaeger_operator_setup/files/operator.yaml"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - opentracing
    - jaeger                   

- name: Wait for the jaeger operator to become available
  shell : "oc rollout status deployment jaeger-operator -n {{ observability }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  
