---
- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ item.project }}"
    params: "{{ item }}"
  with_items: "{{ environments.setup | default([]) }}"

- include_role: 
    name: _cicd_environment_setup

- include_role: 
    name: _monitoring_environment_setup

- include_role: 
    name: _database_environment_setup

- include_role: 
    name: _environments_setup
  vars:
    env: "{{ item }}"     
  with_items: "{{ environments.stages }}"

- include_role: 
    name: _prod_route_setup

- name: initialise the product
  include_role:
    name: _init_product
  vars:
    project: boost-services
  tags:
    - openshift      
 
