---
- include_role: 
    name : init

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-cicd"

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-build"
    
- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-test"
    
- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-mq-blue"        

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-mq-green"

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-prod"

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-monitoring"
