---
- include_role: 
    name : init

- include_role: 
    name: "{{ item.name }}"
  vars:
    params: "{{ item }}"
  with_items: "{{ environments.teardown_roles | default([]) }}"

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-cicd"

- include_role: 
    name: delete-namespace
  vars:
    project: "{{ product }}-{{ item.name }}"     
  with_items: "{{ environments.stages }}"

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-console"

- include_role: 
    name : delete-namespace
  vars:
    project: "{{ product }}-monitoring"