---
- debug:
    var: env
    verbosity: 0

- debug:
    var: next_env
    verbosity: 0

- set_fact: stage_project="{{ product.name }}-{{ env.name }}"

- include_role: 
    name: _namespace_setup
  vars:
    project: "{{ stage_project }}"
    project_description: "{{ env.display }}: {{ product.description }}"
    next: "{{ product.name }}-{{ next_env }}"
    display: "{{ env.display }}"

- include_role: 
    name: _namespace_role_setup
  vars:
    project: "{{ stage_project }}"
    role: env.role
  when: env.role is defined

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ stage_project }}"
    params: "{{ item }}"
  with_items: "{{ env.setup | default([]) }}"

- include_role: 
    name: _add_jenkins_role
  vars:
    project: "{{ stage_project }}"
    role: edit
