---
- set_fact: github_hook_state=present
  when: hook_state is undefined  

- name:  create a new webhook for microservice {{ item.name }}
  github_webhook:
    repository: "{{ github.org }}/{{ item.repo }}"
    url: http://console-gateway-api-{{ product.name }}-console.{{ openshift.apps }}/github/hooks/
    content_type: json
    events:
      - push
    user: "{{ github.user }}"
    password: "{{ github.password }}"
    state: "{{ github_hook_state }}"
  with_items: "{{ microservices }}"

- name:  create a new webhook for test {{ item.test_repo }}
  github_webhook:
    repository: "{{ github.org }}/{{ item.test_repo }}"
    url: http://console-gateway-api-{{ product.name }}-console.{{ openshift.apps }}/github/hooks/
    content_type: json
    events:
      - push
    user: "{{ github.user }}"
    password: "{{ github.password }}"
    state: "{{ github_hook_state }}"
  when: item.test_repo is defined
  with_items: "{{ environments.stages }}"  