---
- set_fact: db_project="{{ product.name }}-database"

- include_role: 
    name: _namespace_setup
  vars:
    project: "{{ db_project }}"
    project_description: "Database: {{ product.description }}"
  when: environments.databases is defined

- include_role: 
    name: _namespace_role_setup
  vars:
    project: "{{ db_project }}"
    role: view
  when: environments.databases is defined    

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ db_project }}"
    params: "{{ item }}"
  with_items: "{{ environments.databases | default([]) }}"   