---
- name: Install Jaeger
  shell: "oc apply -f {{ actions }}/boostcd.jaeger_setup/files/opentracing.yml -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - opentracing
    - jaeger             



    