---

- include_role: 
    name: _webhook_setup

- include_role: 
    name: _update_environments

- include_role: 
    name: _namespace_setup
  vars:
    project: "{{ console_project }}"
    project_description: "Console: {{ product.description }}"

- name: Deploy the console and the proxy
  include_role:
    name: _deploy_boost_service
  vars:
    microservice: "{{ item }}"     
    docker_registry: "{{ console_environment.docker_registry }}"
    maven_mirror_url: "{{ console_environment.maven_mirror_url }}"     
    project: "{{ console_project }}"
  when: (item.name == 'boost-ui') or (item.name == 'proxy-api')
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift
