apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: console-microservice-pipelines
parameters:
- description: Defines the location of the estafet dockerhub
  name: DOCKERHUB
  required: true  
- description: Defines the location of the estafet github (change this if you have forked and want to use another github)
  name: GITHUB
  required: true
- description: Defines name of the microservice
  name: MICROSERVICE_NAME
  required: true
- description: Defines the git repository uri within which the microservice resides
  name: MICROSERVICE_REPO_URI
  required: true    
- description: Defines build pipeline
  name: BUILD_PIPELINE
  required: true   
- description: Defines release pipeline
  name: RELEASE_PIPELINE
  required: true     
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "build-boost-${MICROSERVICE_NAME}"
      type: build
    name: "build-boost-${MICROSERVICE_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/Estafet-LTD/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: MICROSERVICE
            value: ${MICROSERVICE_NAME}                                 
        jenkinsfilePath: setup-environments/pipelines/${BUILD_PIPELINE}
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "release-boost-${MICROSERVICE_NAME}"
      type: release
    name: "release-boost-${MICROSERVICE_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/Estafet-LTD/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: DOCKERHUB
            value: ${DOCKERHUB}
          - name: GITHUB
            value: ${GITHUB}
          - name: REPO
            value: ${MICROSERVICE_REPO_URI}
          - name: MICROSERVICE
            value: ${MICROSERVICE_NAME}                                 
        jenkinsfilePath: setup-environments/pipelines/${RELEASE_PIPELINE}
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0    