apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: library-pipelines
parameters:
- description: Defines the location of the estafet github (change this if you have forked and want to use another github)
  name: GITHUB
  required: true
- description: Defines name of the library
  name: LIBRARY_NAME
  required: true    
- description: Defines the git repository uri within which the library resides
  name: LIBRARY_REPO_URI
  required: true      
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true   
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "build-${LIBRARY_NAME}"
      type: build-library
      product: ${PRODUCT}
    name: "build-${LIBRARY_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}                   
          - name: REPO
            value: ${LIBRARY_REPO_URI}            
        jenkinsfilePath: setup-environments/pipelines/build-library-pipeline.groovy
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: "release-${LIBRARY_NAME}"
      type: release-library
      product: ${PRODUCT}
    name: "release-${LIBRARY_NAME}"
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}             
          - name: REPO
            value: ${LIBRARY_REPO_URI}                       
        jenkinsfilePath: setup-environments/pipelines/release-library-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0