apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: prod-pipelines
parameters:
- description: Defines the location of the estafet github (change this if you have forked and want to use another github)
  name: GITHUB
  required: true  
- description: Defines the host and port for the master node
  name: MASTER_HOST
  required: true  
- description: Defines the admin user
  name: ADMIN_USER
  required: true  
- description: Defines the admin password
  name: ADMIN_PASSWORD
  required: true    
- description: Defines the git repository uri within which the microservice resides
  name: REPO_URI
  required: true       
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: promote-all-to-prod
    name: promote-all-to-prod
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: setup-environments/pipelines/promote-all-to-prod-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: promote-to-live
    name: promote-to-live
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: setup-environments/pipelines/promote-passive-to-live.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0     
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: qa-test
    name: qa-test
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/${REPO_URI}-qa"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}                  
        jenkinsfilePath: openshift/pipelines/qa-tests-pipeline.groovy
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic    
  status:
    lastVersion: 0     
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: prod-test
    name: prod-test
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/${REPO_URI}-qa-prod"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}                  
        jenkinsfilePath: openshift/pipelines/prod-tests-pipeline.groovy
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic    
  status:
    lastVersion: 0           
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: build-all
    name: build-all
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/${REPO_URI}"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: setup-environments/pipelines/build-all-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0     
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: release-all
    name: release-all
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: setup-environments/pipelines/release-all-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0        
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: create-environment
    name: create-environment
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-openshift-boost"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}
          - name: PROJECT_TITLE
            value: null
          - name: MASTER_HOST
            value: ${MASTER_HOST}
          - name: ADMIN_USER
            value: ${ADMIN_USER}
          - name: ADMIN_PASSWORD
            value: ${ADMIN_PASSWORD}            
        jenkinsfilePath: setup-environments/pipelines/create-environment-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0    