apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: global-pipelines
parameters:
- description: Defines the host and port for the master node
  name: MASTER_HOST
  required: true  
- description: Defines the admin user
  name: ADMIN_USER
  required: true  
- description: Defines the admin password
  name: ADMIN_PASSWORD
  required: true    
- description: Defines the git repository uri within which the microservice resides
  name: REPO_URI
  required: true    
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true  
- description: Defines boost version
  name: VERSION
  required: true    
objects:              
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: create-environment
      product: ${PRODUCT}
    name: create-environment
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/Estafet-LTD/estafet-openshift-boost
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: REPO
            value: ${REPO_URI}
          - name: PROJECT_TITLE
            value: "My Project"
          - name: MASTER_HOST
            value: ${MASTER_HOST}
          - name: ADMIN_USER
            value: ${ADMIN_USER}
          - name: ADMIN_PASSWORD
            value: ${ADMIN_PASSWORD}       
          - name: PRODUCT
            value: ${PRODUCT}   
          - name: USER_NAME
            value: "admin"                                   
          - name: USER_ID
            value: "1234"
        jenkinsfilePath: setup-environments/pipelines/create-environment.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0              
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: build-all
      product: ${PRODUCT}
    name: build-all
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/Estafet-LTD/estafet-openshift-boost
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PRODUCT
            value: ${PRODUCT}           
        jenkinsfilePath: setup-environments/pipelines/build-all.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0     
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: release-all
      product: ${PRODUCT}
    name: release-all
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/Estafet-LTD/estafet-openshift-boost
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PRODUCT
            value: ${PRODUCT}        
        jenkinsfilePath: setup-environments/pipelines/release-all.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0    
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: promote-to-live
      product: ${PRODUCT}
    name: promote-to-live
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/Estafet-LTD/estafet-openshift-boost
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PRODUCT
            value: ${PRODUCT}          
        jenkinsfilePath: setup-environments/pipelines/promote-passive-to-live.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0             
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: deploy
    name: deploy
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/Estafet-LTD/estafet-openshift-boost
        ref: ${VERSION}
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PROJECT
            value: project
          - name: PRODUCT
            value: ${PRODUCT}            
          - name: PRODUCT_REPO
            value: repo
          - name: MICROSERVICE
            value: microservice
          - name: VERSION
            value: version
          - name: ENV
            value: ''            
        jenkinsfilePath: setup-environments/pipelines/deploy.jenkinsFile
      type: JenkinsPipeline
  status:
    lastVersion: 0                 