apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: prod-route
parameters:
- description: Defines that hostname of the for the database service
  name: ENV
  value: green 
  required: true
- description: Defines name of the microservice
  name: MICROSERVICE_NAME
  required: true  
objects:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${MICROSERVICE_NAME}
    name: ${MICROSERVICE_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${ENV}${MICROSERVICE_NAME}
      weight: 100
    wildcardPolicy: None