apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: test-pipelines
parameters:
- description: Defines the location of the estafet github (change this if you have forked and want to use another github)
  name: GITHUB
  required: true  
- description: Defines the product that this pipeline is related to
  name: PRODUCT
  required: true
- description: Defines the environment that this pipeline is related to
  name: ENV
  required: true      
- description: Defines repo that contains the test for the specified environment
  name: REPO_URI
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: qa-${ENV}
      product: ${PRODUCT}
    name: qa-${ENV}
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/${REPO_URI}"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}           
          - name: PRODUCT
            value: ${PRODUCT}     
          - name: REPO
            value: ${REPO_URI}
          - name: PROJECT
            value: some_project                                                
        jenkinsfilePath: openshift/pipelines/test.jenkinsFile
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic    
  status:
    lastVersion: 0          