---
- debug:
    var: microservice
    verbosity: 0

- set_fact:
    image_deployed: false
    image: "{{ dockerhub.url }}/{{ dockerhub.org }}/{{ microservice.name }}:{{ microservice.version }}"
    dc_image: ""

- debug:
    var: image
    verbosity: 0

- name: Retrieve the deployment config descriptor
  shell: "oc get dc --selector app={{ microservice.name }} -o json -n {{ project }}"
  register: list_of_dcs

- name: Get the image used by the dc
  set_fact: 
    dc_image: "{{list_of_dcs.stdout|from_json|json_query('items[0].spec.template.spec.containers[0].image')}}"
  ignore_errors: yes

- debug:
    var: dc_image
    verbosity: 0

- set_fact:
    image_deployed: true
  when: image == dc_image

- name: Checkout {{ microservice.name }} from github branch {{ microservice.version }}
  git:
    repo: "{{ microservice.repo }}"
    dest: "{{ workdir }}/{{ microservice.name }}"
    version: "{{ microservice.version }}"
    update: yes
  when: image_deployed == false
  tags:
    - git  

- name: Check that the local-setup.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/setup/local-setup.yml"
  register: stat_result

- name: load the settings
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/setup/local-setup.yml"
  when: stat_result.stat.exists

- include_role: 
    name: "{{ item.name }}"
  vars:
    params: "{{ item }}"
  with_items: "{{ setup | default([]) }}"
  when: stat_result.stat.exists and image_deployed == false

- name: Remove all aspects of the application so that we can rebuild from scratch
  shell: "oc delete all -l app={{ microservice.name }} -n {{ project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: image_deployed == false
  tags:
    - openshift  

- name: Delete the {{ microservice.name }} configmap
  shell: 'oc delete configmap {{ microservice.name }} -n {{ project }} || true'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: image_deployed == false
  tags:
    - openshift

- name: Delete the {{ microservice.name }} secret
  shell: 'oc delete secret {{ microservice.name }} -n {{ project }} || true'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: image_deployed == false
  tags:
    - openshift

- name: Load the variables from local-config.yml
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/local-config.yml"

- name: Initialise config map variables
  set_fact: mapStr=""

- name: format the configmap variables
  set_fact: mapStr="{{ mapStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ config_map }}"

- name: Create the {{ microservice.name }} configmap
  shell: 'oc create configmap {{ microservice.name }} {{ mapStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: image_deployed == false
  tags:
    - openshift

- name: Check that the local-secret.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/local-secret.yml"
  register: stat_result

- name: Load the variables from local-secrets.yml
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/local-secret.yml"
  when: stat_result.stat.exists

- name: Initialise secret variables
  set_fact: secretStr=""
  when: stat_result.stat.exists

- name: format the secrets variables
  set_fact: secretStr="{{ secretStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ secrets }}"
  when: stat_result.stat.exists

- name: Create the {{ microservice.name }} secrets
  shell: 'oc create secret generic {{ microservice.name }} {{ secretStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: stat_result.stat.exists and image_deployed == false
  tags:
    - openshift

- name: Load the variables from default-resources.yml
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/default-resources.yml"

- name: Create the deployment config
  shell: "oc process -n {{ project }} -f {{ workdir }}/{{ microservice.name }}/src/boost/openshift/templates/deploy-config.yml -p MICROSERVICE={{ microservice.name }} -p NAMESPACE={{ project }} -p DOCKER_NAMESPACE={{ dockerhub.org }} -p DOCKER_IMAGE_LABEL={{ microservice.version }} -p DOCKER_REGISTRY={{ dockerhub.url }} -p PRODUCT={{ product.name }} -p MAX_MEMORY={{ resources.max_memory }} -p MIN_MEMORY={{ resources.min_memory }} -p MAX_CPU={{ resources.max_cpu }} -p MIN_CPU={{ resources.min_cpu }} -p REPLICAS={{ resources.replicas }} | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: image_deployed == false
  tags:
    - openshift     

- name: Wait for the microservice to become available {{ microservice.name }}
  shell: "oc rollout status dc/{{ microservice.name }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: image_deployed == false
  tags:
    - openshift

- name: Expose Service {{ microservice.name }}
  shell: "oc expose service {{ microservice.name }}"
  when: microservice.expose and image_deployed == false
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift