---
- include_role: 
    name : init

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ item.project }}"
    params: "{{ item }}"
  when: environments.roles is defined
  with_items: "{{ environments.roles }}"
  
- include_role: 
    name: environments-setup
  vars:
    env: "{{ item }}"     
  with_items: "{{ environments.stages }}"

- include_role: 
    name: cicd-environment-setup