---
- include_role: 
    name : init

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ item.project }}"
    params: "{{ item }}"
  with_items: "{{ environments.roles | default([]) }}"

- include_role: 
    name: cicd-environment-setup

- include_role: 
    name: environments-setup
  vars:
    env: "{{ item }}"     
  with_items: "{{ environments.stages }}"

