---
- set_fact: monitoring_project="{{ product.name }}-monitoring"

- include_role: 
    name: boostcd._namespace_setup
  vars:
    project: "{{ monitoring_project }}"
    project_description: "Monitoring: {{ product.description }}"
  when: environments.monitoring is defined

- include_role: 
    name: boostcd._namespace_role_setup
  vars:
    project: "{{ monitoring_project }}"
    role: view
  when: environments.monitoring is defined    

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ monitoring_project }}"
    params: "{{ item }}"
  with_items: "{{ environments.monitoring | default([]) }}"    
