---
- name: Retrieve the list of users
  shell: "oc get users -o json"
  register: users_json     

- name: Get the names of the users
  set_fact: users="{{users_json.stdout|from_json|json_query('items[*].metadata.name')}}"
  
- name: Allow users to access project
  shell: 'oc policy add-role-to-user {{ role }} {{ item }}'
  when: "{{ item != 'admin' }}"
  with_items: "{{ users }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

    