---
- name: Allow users to access {{ project }} with role {{ role }}
  shell: 'oc policy add-role-to-user {{ role }} {{ item.name }} -n {{ project }}'
  with_items: "{{ users }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

    