---
- name: Create the admin annotator
  shell: "oc apply -f {{ objects }}/admin-annotator.yaml"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - openshift  