---
- set_fact: db_project="{{ product }}-db"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ db_project }}"
    project_description: "Database: {{ product_description }}"
  when: environments.db is defined

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ db_project }}"
    role: view
  when: environments.db is defined    

- include_role: 
    name: "{{ item.name }}"
  vars:
    project: "{{ db_project }}"
    params: "{{ item }}"
  with_items: "{{ environments.db | default([]) }}"   