---
- name: Delete {{ component }}
  shell: "kubectl delete -n {{ project }} -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/{{ component }}.yaml"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - opentracing
    - jaeger   