---
- name: Check that the {{ stage }}-init.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/init/{{ stage }}-init.yml"
  register: stat_result

- name: define the init file
  set_fact:
    init_yml: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/init/{{ stage }}-init.yml"
  when: stat_result.stat.exists  

- name: Check that the default-init.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/init/default-init.yml"
  register: stat_result
  when: init_yml is undefined

- name: define the setup file
  set_fact:
    init_yml: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/init/default-init.yml"
  when: stat_result.stat.exists and init_yml is undefined  

- name: load the init settings
  include_vars:
    file: "{{ init_yml }}"
  when: init_yml is defined

- include_role: 
    name: "{{ item.name }}"
  vars:
    params: "{{ item }}"
  with_items: "{{ init | default([]) }}"
  when: init_yml is defined    