---
- name: Verify if variables are set
  fail:
    msg: "[Work directory] is not defined. Please edit vars.yml"
  when: (workdir is undefined)

- name: Create Workdir
  file:
    path: "{{ workdir }}"
    state: directory

- name: Checkout the boost console dependencies from github
  git:
    repo: "https://github.com/{{ github }}/estafet-openshift-boost.git"
    dest: "{{ workdir }}/estafet-openshift-boost"
    update: yes
  tags:
    - git  
    
- name: Install boost roles
  copy:
    src: "{{ workdir }}/estafet-openshift-boost/setup-environments/roles"
    dest: /etc/ansible/roles
    force: yes
