---
# Define the name and description of the OpenShift project
- set_fact: boost_project="boost-cicd"

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ boost_project }}"
    project_description: "Boost Development"

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ boost_project }}"
    role: edit

- include_role: 
    name: jenkins-setup
  vars:
    project: "{{ boost_project }}"
    volume_capacity: 30Gi
    memory_limit: 3Gi

- name: Delete the all pipelines
  shell: "oc delete bc --all -n {{ boost_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  tags:
    - openshift 

- include_role: 
    name: boost-libraries-setup
  vars:
    project: "{{ boost_project }}"