---
- set_fact: branch="master"

- debug:
    var: microservice
    verbosity: 0

- name: fetch latest tag for this repo
  shell: "git describe --abbrev=0 --tags"
  args:
    chdir: "{{ workdir }}/{{ microservice.name }}"
  when: (microservice.test is defined and microservice.test == true) or (test is defined and test == true)
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - git  

- set_fact: branch="{{ command_result.stdout }}"
  when: (microservice.test is defined and microservice.test == true) or (test is defined and test == true)

- set_fact: branch="{{ microservice.branch }}"
  when: microservice.branch is defined

- name: Checkout {{ microservice.name }} from github branch {{ branch }}
  git:
    repo: "{{ microservice.repo }}"
    dest: "{{ workdir }}/{{ microservice.name }}"
    version: "{{ branch }}"
    update: yes
  tags:
    - git  

- name: Check that the local-setup.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/setup/local-setup.yml"
  register: stat_result

- name: load the settings
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/setup/local-setup.yml"
  when: stat_result.stat.exists

- include_role: 
    name: "{{ item.name }}"
  vars:
    params: "{{ item }}"
  with_items: "{{ setup | default([]) }}"
  when: stat_result.stat.exists

- name: Remove all aspects of the application so that we can rebuild from scratch
  shell: "oc delete all -l app={{ microservice.name }} -n {{ project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  

- set_fact: imagestream_namespace="openshift"
  when: microservice.imagestream_namespace is undefined

- set_fact: imagestream_namespace="{{ microservice.imagestream_namespace }}"
  when: microservice.imagestream_namespace is defined

- name: Create the {{ microservice.name }} build config from {{ branch }} branch
  shell: 'oc process -n {{ project }} -f {{ workdir }}/{{ microservice.name }}/src/boost/openshift/templates/build-config.yml -p MICROSERVICE={{ microservice.name }} -p MICROSERVICE_REPO_URI={{ microservice.repo }} -p NAMESPACE={{ project }} -p IMAGESTREAM_NAMESPACE={{ imagestream_namespace }} -p DOCKER_IMAGE_LABEL=latest -p PRODUCT={{ product.name }} -p MAVEN_MIRROR_URL={{ maven_mirror_url }} -p DOCKER_REGISTRY={{ docker_registry }} -p SOURCE_REPOSITORY_REF={{ branch }} | oc apply -f -'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift             

- name: Start the {{ microservice.name }} build
  shell: 'oc start-build {{ microservice.name }} --wait -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Delete the {{ microservice.name }} configmap
  shell: 'oc delete configmap {{ microservice.name }} -n {{ project }} || true'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Delete the {{ microservice.name }} secret
  shell: 'oc delete secret {{ microservice.name }} -n {{ project }} || true'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Load the variables from local-config.yml
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/local-config.yml"

- name: Initialise config map variables
  set_fact: mapStr=""

- name: format the configmap variables
  set_fact: mapStr="{{ mapStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ config_map }}"

- name: Create the {{ microservice.name }} configmap
  shell: 'oc create configmap {{ microservice.name }} {{ mapStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Check that the local-secret.yml exists
  stat:
    path: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/local-secret.yml"
  register: stat_result

- name: Load the variables from local-secrets.yml
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/local-secret.yml"
  when: stat_result.stat.exists

- name: Initialise secret variables
  set_fact: secretStr=""
  when: stat_result.stat.exists

- name: format the secrets variables
  set_fact: secretStr="{{ secretStr }} --from-literal={{ item.name }}='{{ item.value }}'"
  with_items: "{{ secrets }}"
  when: stat_result.stat.exists

- name: Create the {{ microservice.name }} secrets
  shell: 'oc create secret generic {{ microservice.name }} {{ secretStr }} -n {{ project }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  when: stat_result.stat.exists
  tags:
    - openshift

- name: Load the variables from default-resources.yml
  include_vars:
    file: "{{ workdir }}/{{ microservice.name }}/src/boost/openshift/configuration/default-resources.yml"

- name: Create the deployment config
  shell: "oc process -n {{ project }} -f {{ workdir }}/{{ microservice.name }}/src/boost/openshift/templates/deploy-config.yml -p MICROSERVICE={{ microservice.name }} -p NAMESPACE={{ project }} -p DOCKER_NAMESPACE={{ project }} -p DOCKER_IMAGE_LABEL=latest -p DOCKER_REGISTRY={{ docker_registry }} -p PRODUCT={{ product.name }} -p MAX_MEMORY={{ resources.max_memory }} -p MIN_MEMORY={{ resources.min_memory }} -p MAX_CPU={{ resources.max_cpu }} -p MIN_CPU={{ resources.min_cpu }} -p REPLICAS={{ resources.replicas }} | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift     

- name: Wait for the microservice to become available {{ microservice.name }}
  shell: "oc rollout status dc/{{ microservice.name }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Expose Service {{ microservice.name }}
  shell: "oc expose service {{ microservice.name }}"
  when: microservice.expose
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift