---
- name: Build and Deploy console app
  hosts: local  
  tasks:   

    - name: determine where oc is installed
      shell: which oc
      register: which
    
    - debug: msg="{{ which.stdout }}"
    - debug: msg="{{ which.stderr }}"

    - name: determine the version of oc
      shell: oc version
      register: version
    
    - debug: msg="{{ version.stdout }}"
    - debug: msg="{{ version.stderr }}"

    - name: Verify that the env_project variable is set
      fail:
        msg: "[env_project variable definition] is not set."
      when: env_project is undefined

    - name: Verify that the microservice variable is set
      fail:
        msg: "[target_app variable definition] is not set."
      when: target_app is undefined

    - include_role:
        name: _build_console_app
      vars: 
        project: "{{ env_project }}"

