---
- name: Install Developer Environment
  hosts: local 
  tasks:   
  
    - name: load the variables
      include_vars:
        dir: ../definitions
        extensions: [yml]  

    - name: Verify that the env_project variable is set
      fail:
        msg: "[env_project variable definition] is not set."
      when: env_project is undefined

    - name: Verify if the environments have been defined
      fail:
        msg: "[Developer environment definition] are not set. Please edit developer-environment.yml"
      when: developer_environment is undefined
            
    - include_role:
        name: boostcd._environment_setup
      vars:
        env: "{{ developer_environment }}" 
        
