---
- name: Preparing the ansible roles for openshift boost 
  hosts: local   
  tasks:

    - name: load the variables
      include_vars:
        dir: ../definitions
        extensions: [yml]  
   
    - set_fact: 
        workdir: "{{ ansible_env.HOME }}/.boost"

    - name: Create Workdir
      file:
        path: "{{ workdir }}"
        state: directory
        
    - name: Checkout the boost console dependencies from github
      git:
        repo: "{{ boost.repo }}"
        dest: "{{ workdir }}/boostcd"
        version: "{{ boost.version }}"
        update: yes
      tags:
        - git  

    - name: Updating boost playbooks and inventory
      synchronize:
        src: "{{ workdir }}/boostcd/src/boost/openshift/playbooks"
        dest: "{{ playbook_dir }}/.."
        recursive: yes
        delete: yes

    - name: Updating boost roles
      synchronize:
        src: "{{ workdir }}/boostcd/src/boost/openshift/roles"
        dest: "~/.ansible"    
        recursive: yes
        delete: yes        

    - name: Check that the product roles exist
      stat:
        path: "{{ playbook_dir }}/roles"
      register: product_roles

    - name: Updating product roles
      copy:
        src: "{{ playbook_dir }}/roles"
        dest: "~/.ansible"
        force: yes   
      when: product_roles.stat.exists and product_roles.stat.isdir

    - name: Install jmespath
      shell: "pip install --user jmespath"
      register: command_result
      failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
      changed_when: "'exists' not in command_result.stderr"
      tags:
        - jmespath 