---
- name: Install Local Environment
  hosts: local 
  tasks:   

    - name: load the variables
      include_vars:
        dir: ../definitions
        extensions: [yml]  
    
    - name: Verify if the environments have been defined
      fail:
        msg: "[Local environment definition] are not set. Please edit local-environment.yml"
      when: local_environment is undefined
            
    - include_role:
        name: _environment_setup
      vars:
        env: "{{ local_environment }}" 
        
