---
- name: Install QA Environment
  hosts: local 
  tasks:         
  
    - name: load the variables
      include_vars:
        dir: ../definitions
        extensions: [yml]  
        
    - name: Verify if the environments have been defined
      fail:
        msg: "[QA environment definition] are not set. Please edit qa-environment.yml"
      when: qa_environment is undefined
            
    - include_role:
        name: _environment_setup
      vars:
        env: "{{ qa_environment }}" 
