---
- name: create git repostories if required
  include_role: 
    name: _git_repo_setup

- name: create the webhooks for git repostories
  include_role: 
    name: _webhook_setup

- name: deploy the environments
  include_role: 
    name: _update_environments

- name: create the console namespace
  include_role: 
    name: _namespace_setup
  vars:
    project: "{{ console_project }}"
    project_description: "Console: {{ product.description }}"

- name: Deploy the console and the proxy
  include_role:
    name: _deploy_boost_service
  vars:
    microservice: "{{ item }}"     
    docker_registry: "{{ console_environment.docker_registry }}"
    maven_mirror_url: "{{ console_environment.maven_mirror_url }}"     
    project: "{{ console_project }}"
    stage: live
  when: (item.name == 'boost-ui') or (item.name == 'proxy-api')
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift
  
