---
# Define the name and description of the OpenShift project
- set_fact: nexus_project="nexus"

- include_role: 
    name : init

- include_role: 
    name: namespace-setup
  vars:
    project: "{{ nexus_project }}"
    project_description: "Nexus"
    cloud_environment: true

- include_role: 
    name: namespace-role-setup
  vars:
    project: "{{ nexus_project }}"
    role: view

- name: Install the Nexus repository server
  shell: "oc new-app sonatype/nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  
    
- name: Ensure that nexus runs on the infrastructure nodes
  shell: "oc patch dc/nexus -p '{\"spec\":{\"template\":{\"nodeSelector\":{\"node-role.kubernetes.io/infra\":\"true\"}}}}'"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus     
    
- name: Wait for the nexus server to become available
  shell: "oc rollout status dc/nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Expose the nexus service
  shell: "oc expose svc/nexus --path='/nexus'"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Configure the liveness probe
  shell: "oc set probe dc/nexus --liveness --failure-threshold 3 --initial-delay-seconds 30 -- echo ok"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Configure the readiness probe
  shell: "oc set probe dc/nexus --readiness --failure-threshold 3 --initial-delay-seconds 30 --get-url=http://:8081/nexus/content/groups/public"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Wait for the nexus server to become available
  shell: "oc rollout status dc/nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus      

- name: Configure the persistent storage for nexus
  shell: "oc volume dc/nexus --add --name 'nexus-volume-1' --type 'pvc' --mount-path '/sonatype-work/' --claim-name 'nexus-pv' --claim-size '10G' --overwrite"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  

- name: Wait for the nexus server to become available
  shell: "oc rollout status dc/nexus"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - nexus  
    