---
- debug:
    var: params
    verbosity: 0

- name: Load Json to wiremock
  uri:
    url: http://wiremock.{{ project }}.svc:8080/__admin/mappings/new
    method: POST
    src: "{{ json }}"
    status_code: 201