---
- name: read ansible vault file and encode is into base64
  set_fact:
    vault_contents_bytes: "{{lookup('file', '~/ansible_vault', rstrip=true) | b64decode }}"

- debug:
    var: vault_contents_bytes
    verbosity: 0

- name: Set ansible vault password
  xml:
    path: "{{ role_path }}/files/credentials.xml"
    xpath: /com.cloudbees.plugins.credentials.SystemCredentialsProvider/domainCredentialsMap/entry/java.util.concurrent.CopyOnWriteArrayList/org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl/secretBytes
    value: "{{ vault_contents_bytes }}"