---
- include_role: 
    name: namespace-setup
  vars:
    project: "{{ console_project }}"
    project_description: "Console: {{ product.description }}"

- include_role: 
    name: amq-setup
  vars:
    project: "{{ console_project }}"
    params: "{{ amq_params }}"

- include_role: 
    name: postgresql-setup
  vars:
    project: "{{ console_project }}"

- include_role: 
    name: jaeger-setup
  vars:
    project: "{{ console_project }}"

- name: Deploy the console and the proxy
  include_role:
    name: deploy-console-app
  vars:
    microservice: "{{ item }}"     
    docker_registry: "{{ console_environment.docker_registry }}"
    maven_mirror_url: "{{ console_environment.maven_mirror_url }}"     
    project: "{{ console_project }}"
  when: (item.name == 'boost-ui') or (item.name == 'proxy-api')
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift

- include_role: 
    name: namespace-setup
  vars:
    project: boost-services
    project_description: "Boost Services"

- name: Deploy the boost microservices
  include_role:
    name: deploy-console-app
  vars:
    microservice: "{{ item }}"     
    docker_registry: "{{ console_environment.docker_registry }}"
    maven_mirror_url: "{{ console_environment.maven_mirror_url }}"     
    project: boost-services
  when: (item.name != 'boost-ui') and (item.name != 'proxy-api') and ((item.conditional is undefined) or (item.conditional == 'jira' and jira is defined) or (item.conditional == 'trello' and trello is defined))
  with_items: "{{ boost_microservices }}"
  tags:
    - openshift

- name: 
  include_role:
    name: boostcd.init_product
  vars:
    project: boost-services
  tags:
    - openshift    
