---
- name:  delete the new webhook for microservice {{ item.name }}
  github_webhook:
    repository: "{{ item.repo | github_webhook_repo }}"
    url: "http://console-gateway-api-{{ product.name }}-console.{{ openshift.subdomain }}/github/hooks/"
    user: "{{ github.user }}"
    password: "{{ github.password }}"
    state: absent
  with_items: "{{ microservices }}"

- name:  delete the new webhook for test {{ item.test_repo }}
  github_webhook:
    repository: "{{ item.test_repo | github_webhook_repo }}"
    url: "http://console-gateway-api-{{ product.name }}-console.{{ openshift.subdomain }}/github/hooks/"
    user: "{{ github.user }}"
    password: "{{ github.password }}"
    state: absent
  when: item.test_repo is defined
  with_items: "{{ environments.stages }}"  