---
- name: Switch to Namespace {{ cicd_project }}
  shell: "oc project {{ cicd_project }}"
  tags:
    - openshift  

- name: Delete the build pipelines
  shell: "oc delete bc build-{{ item.name }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ microservices }}"
  tags:
    - openshift 

- name: Delete the release pipelines
  shell: "oc delete bc release-{{ item.name }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ microservices }}"
  tags:
    - openshift 

- name: Delete the test pipelines
  shell: "oc delete bc test-{{ item.name }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ microservices }}"
  tags:
    - openshift 

- name: Delete the promote-to-prod pipelines
  shell: "oc delete bc promote-to-prod-{{ item.name }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: "{{ microservices }}"
  tags:
    - openshift 

- name: Delete the promote pipelines
  shell: "oc delete bc promote-{{ item[1].name }}-{{ item[0].name }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  when: item[1].name != 'build' and item[1].name != 'prod' and item[1].next != 'end' 
  with_nested: 
    - "{{ microservices }}"
    - "{{ environments.stages }}"
  tags:
    - openshift 

- name: Delete the promote all pipelines
  shell: "oc delete bc promote-all-{{ item.name }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  when: item.name != 'build' and item.name != 'prod' and item.next != 'end' 
  with_items: "{{ environments.stages }}"
  tags:
    - openshift 

- name: Delete the the other pipelines
  shell: "oc delete bc {{ item }} -n {{ cicd_project }} || true"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"  
  with_items: 
    - promote-all-to-prod
    - create-environment
    - build-all
    - release-all
    - promote-to-live
    - deploy
  tags:
    - openshift 
