---
# Project definition - add new microservices here
microservices_boost_projects:
  - name: console-feature-api
    repo: estafet-openshift-boost-console-api-feature
    db: true
    expose: false       
    environment_variables:        
      - name: OPENSHIFT_HOST_PORT
        value: "{{ openshift }}"
      - name: OPENSHIFT_USER
        value: "{{ username }}"
      - name: OPENSHIFT_PASSWORD
        value: "{{ password }}"      
        
    